GET http://localhost:5000/chain-data

###

GET http://localhost:5000/chain-data/624934b74681c620158023b9

###

POST http://localhost:5000/chain-data
Content-Type: application/json

{
    "chain": "ethereum",
    "account": "0x12A0c672fa0F896d72F62e7D572d1a745B86f279",
    "symbol": "ETH"
}

###

DELETE http://localhost:5000/chain-data/628bf396824858a46898d0b0

###

GET http://localhost:5000/chain-data/form-data

###

GET http://localhost:5000/price

###

GET http://localhost:5000/price/?ticker=eth-ethereum,hex-hex

###

GET http://localhost:5000/price/?ticker=eth-ethereum

# eth addresses example
#0x165CD37b4C644C2921454429E7F9358d18A45e14
#0xb77e1dae0b8ec6b7cbb64ac3a0149c401cc4a9cf